### ISSUE TITLE
Image Migration to Imgur

### ISSUE THREAD

**Issue by right-mouse** [Emseers/Emseers.github.io#14]
We need to have all images that are not already in the repository to be in one organized place - Imgur. Some images on the website currently need to be migrated to imgur, like the screenshots on the index page.

**Comment by right-mouse** [comment]
07be29cf0b3a8a26e714f8b479d6b1e66293b3c5

**Comment by boarnoah** [comment]
Issue fixed, in the future we can use the Imgur acc (details were emailed)
