### ISSUE TITLE
Look into changing font of text that is viewed through an ifame (if possible)

### ISSUE THREAD

**Issue by right-mouse** [Emseers/Emseers.github.io#15]
Currently, the font of the stuff in blogIndex.html (viewed only through an iframe in other pages) is not consistent with the font of the rest of the website. The font-family in the css for the whole website is currently
`font-family: Verdana, "Bitstream Vera Sans", sans-serif;`
@Emseers/emseers_devteam Look into making this the font of the text viewed through this iframe this font, if at all possible.

**Comment by boarnoah** [comment]
Might be the " in the Bitsream part not being properly escaped. Not sure if html escape chars have any effect for styles. @arvindmc 

Can't test this myself since I can't tell the difference between fonts

![testfont](https://cloud.githubusercontent.com/assets/10406608/11922741/d56e7000-a767-11e5-8769-02d9218556e9.png)

**Comment by right-mouse** [comment]
I do believe the " is being properly escaped (see the example on [this page](http://www.w3schools.com/cssref/pr_font_font-family.asp). As you can see, the font inside the iFrame (look at the title of the blog) is a serif font, while thes rest is sans-serif. Adding font family inside the html file for the iFrame itself has no effect as far as I can tell. My guess to solving this would be to maybe run some js code to change the font after the website is loaded, though I'm not sure if the innerHTML of iFrames are accessible at all...

**Comment by boarnoah** [comment]
As discussed apparently there is indeed an issue with the " it was solved with either replacing " with ' or neither. 
http://stackoverflow.com/a/5353013/4433646 (note the &qout seems to have an issue with older IE versions and doesn't work on my version of Firefox either).
