### ISSUE TITLE
Colours be a bit garish

### ISSUE THREAD

**Issue by boarnoah** [Emseers/Emseers.github.io#2]
Needs a bit of think @poisonrune some help here?
http://snag.gy/UGpMT.jpg

**Comment by boarnoah** [comment]
My entries: 
http://imgur.com/a/myvr8
Ill put full links here:
![theme1](https://cloud.githubusercontent.com/assets/10406608/6201011/d67af9b4-b460-11e4-84ac-d96040175800.png)
![theme2](https://cloud.githubusercontent.com/assets/10406608/6201013/d68de5ce-b460-11e4-92b4-a16b76522a96.png)
![theme3](https://cloud.githubusercontent.com/assets/10406608/6201015/d69d392a-b460-11e4-84e5-9bfd5e22bf3a.png)
![theme4](https://cloud.githubusercontent.com/assets/10406608/6201014/d693a69e-b460-11e4-80ac-c7462133f908.png)
![theme5](https://cloud.githubusercontent.com/assets/10406608/6201016/d6a3673c-b460-11e4-9edf-cdd3af21a407.png)
![theme6](https://cloud.githubusercontent.com/assets/10406608/6201012/d686ea44-b460-11e4-9182-bc22d81e8b27.png)

**Comment by right-mouse** [comment]
My entries:

![preview](https://cloud.githubusercontent.com/assets/10985546/6201026/3e92ac68-b461-11e4-800e-8a9a75965d10.png)

**Comment by boarnoah** [comment]
Sirrams vote is for 3 or 6 on mine.
Shadowryas vote is for Arvinds last one but without a green bckg.

**Comment by ghost** [comment]
4 for adipa's entry and 3 in arvind's entry

**Comment by boarnoah** [comment]
So overall Arvinds last one and my 4 had the most votes.
So bascially a nice light emseers coloured theme, similar to twitters theme in fact.

**Comment by ghost** [comment]
I think the cyan in the background for your entry is a bit off, maybe change it to a more dull color

**Comment by boarnoah** [comment]
http://snag.gy/GgFr5.jpg
How does this look?
Latest:
http://snag.gy/FVfhB.jpg

**Comment by boarnoah** [comment]
And arvind has this:
http://snag.gy/Njfip.jpg

**Comment by ghost** [comment]
yeah arvind's is very good now, i still dislike the orangy buttons

**Comment by boarnoah** [comment]
Yeah buttons are wip, thats not going to stay oragne for long.
