### ISSUE TITLE
Blog page

### ISSUE THREAD

**Issue by boarnoah** [Emseers/Emseers.github.io#6]
Blog page, looked into wordpress integration but thats php and we don't have any server compute. So either figure out some javascript based solution or lets just do it in html ourselves (similar to a few other sites).

**Comment by right-mouse** [comment]
The plan is to put it on the right side of the website opposite to the twitter widget and see how that'll look.

**Comment by boarnoah** [comment]
Baring future hosting where we can use wordpress the blog pages are handled as seperate html pages, the "index" box on the side is handled as a seperate page that loads in as a iframe instead of using javascript. 
Will be an issue in the future when the list gets long enough, good enough for now.
